Added support for setting keyboard/display backlight.

diff --git a/usr/bin/mba-backlight b/usr/bin/mba-backlight
--- a/usr/bin/mba-backlight
+++ b/usr/bin/mba-backlight
@@ -4,40 +4,41 @@ set -e
 
 # Script for setting MacBookAir6,2 backlight
 
-BACKLIGHT_DEVICE="/sys/class/backlight/mba6x_backlight"
+. /usr/lib/device-macbookair62/backlight.sh
 
-if [ ! -d "${BACKLIGHT_DEVICE}" ]
+
+DISPLAY_DEVICE="/sys/class/backlight/mba6x_backlight"
+KEYBOARD_DEVICE="/sys/class/leds/smc::kbd_backlight"
+#KEYBOARD_DEVICE="/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight"
+
+usage() {
+    echo "Usage: $0 [-d VAL] [-k VAL]"
+    echo " where -d VAL specifies display brightness"
+    echo " and   -k VAL specifies keyboard brightness"
+}
+
+
+if [ -z "$1" ]
 then
-    echo "E: Backlight control device not found!"
+    usage
     exit 1
 fi
 
-CTRL_FILE="${BACKLIGHT_DEVICE}/brightness"
-
-CURRENT_VALUE="$(cat ${CTRL_FILE})"
-MIN_VALUE="0"
-MAX_VALUE="$(cat ${BACKLIGHT_DEVICE}/max_brightness)"
-
-echo "Current brightness: ${CURRENT_VALUE}. Maximum: ${MAX_VALUE}."
-
-NEW_VALUE="$1"
-if [ -n "${NEW_VALUE}" ]
-then
-    if [ -w "${CTRL_FILE}" ]
-    then
-        if [ "${NEW_VALUE}" -lt "${MIN_VALUE}" ]
-        then
-            echo "Value too small: ${NEW_VALUE} < ${MIN_VALUE}."
-        elif [ "${NEW_VALUE}" -gt "${MAX_VALUE}" ]
-        then
-            echo "Value too large: ${NEW_VALUE} > ${MAX_VALUE}."
+while getopts k:d: OPT
+do
+    case "${OPT}" in
+        k)
+            echo "Setting keyboard backlight brightness..."
+            do_backlight "${KEYBOARD_DEVICE}" "${OPTARG}" || fial "Can't set keyboard backlight brightness."
+        ;;
+        d)
+            echo "Setting display brightness..."
+            do_backlight "${DISPLAY_DEVICE}" "${OPTARG}" || fail "Can't set display brightness."
+        ;;
+        *)
+            echo "Invalid arguments passed."
+            usage
             exit 1
-        else
-            echo "Set brightness: ${NEW_VALUE}."
-            echo "${NEW_VALUE}" >${CTRL_FILE}
-        fi
-    else
-        echo "You have no permission to change display brightness."
-        exit 1
-    fi
-fi
+        ;;
+    esac
+done
